### ISSUE TITLE
Production API 

### ISSUE THREAD

**Issue by demesg** [DSorlov/frejaadmin#5]
Hi Daniel, 
Is there an easy way to switch to production API? It seems to be hardcoded against freja test environment.

By the way, I really like your work, your work has really contributed to the eID scene In Sweden! thank you.
//magnus

**Comment by DSorlov** [comment]
Hi!
You should get a manual configuration object like so:

// get the provider itself
const eidprovider   = require('eid-provider')('frejaeid');

//inside eidconfig you have all config use either production or testing
const eidconfig = eidprovider.settings['production'];
//you could change whatever setting you need here and then 

// initialize using the config above
eidprovider.initialize(eidconfig);
